config/routes.rb
FoodTracker::Application.routes.draw do

  devise_for :users,
  :controllers => {
  #sessions: "sessions",
  #registrations: "registrations"
  }

  resources :activities
  resources :reports, except: [:destroy, :update ]

  root to: 'activities#index'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :category_id, :description, :user_id, :category, :date

  belongs_to :category
  belongs_to :user

  validates :user_id, :category_id, :description, :date, presence: true
  validate :validate_weight

  def self.latest(user)
    activities = self.fetch(user)

    # group by date
    activities_by_date = activities.inject(Hash.new{|h,k| h[k] = [] }) {|h, object| h[object.date] << [object.category_id, [object.id, object.description]]; h }

    # group by category in date subarray
    activities_by_category = {}
    activities_by_date.each do |date, hash|
      activities_by_category[date] ||= {}
      hash.each do |k,v|
        activities_by_category[date][k] ||= []
        activities_by_category[date][k] << v
      end

      # sort by category id
      activities_by_category[date] = activities_by_category[date].sort
    end

    # add dates with empty activities
    #for day in period_start..period_end
    #  day = day.to_s("%Y-%m-%d")
    #  activities_by_category[day] = {} if activities_by_category[day].nil?
    #end

    # sort by date
    activities_by_category.sort.reverse
  end

  def self.for_report(user, period_start, period_end)
    activities = self.fetch(user, period_start, period_end)

    # group by date
    activities_by_date = activities.inject(Hash.new{|h,k| h[k] = {} }) do |h, object|
      h[object.date] ||= {}
      h[object.date][object.category_id] ||= []
      h[object.date][object.category_id] << object.description
      h
    end

    # sort by date
    activities_by_date.sort.reverse
  end

  def self.fetch(user, period_start = 10.years.ago, period_end = Date.today)
    activities = Activity.select("id, to_char(date, 'YYYY-MM-DD') as date, category_id, description").where("user_id = ? and date BETWEEN ? and ? ",user.id, period_start, period_end ).group("to_char(date, 'YYYY-MM-DD'), id, category_id, description")
  end


  def validate_weight
    if category.present? && category.is_weight? && description.to_f.zero?
      errors.add(:description, 'should be numerical')
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :activities, dependent: :destroy

  validates :name, presence: true

  def is_weight?
    name.eql?('Weight')
  end

end

app/models/report.rb
class Report < ActiveRecord::Base

  validates :period_start, :period_end, :user_id, :email, :subject, presence: true
  attr_accessible :period_start, :period_end, :email, :subject, :comments

  before_create :generate_key
  after_create :send_email

  belongs_to :user

  def to_param
    key
  end

  PERIODS = {
    'All days'      => 'all_days',
    'Last 30 days'  => '30_days',
    'Last 7 days'   => '7_days',
    'Last 24 hours' => '24_hours'
  }

  def self.date_range(period)
    case period
      when '30_days'
        [ 30.days.ago, Date.today ]
      when '7_days'
        [ 7.days.ago, Date.today ]
      when '24_hours'
        [ Date.yesterday, Date.today ]
      else
        [ 10.years.ago.to_date, Date.today.to_date ]
    end
  end

protected

  def generate_key
    self.key = UUID.new.generate[0,18].gsub('-','')
  end

  def send_email
    Mailer.share_report(self).deliver
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  before_save :ensure_authentication_token

  has_many :activities
  has_one :report

  def as_json(options)
    super(options).merge(auth_token: authentication_token)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_resource, only: [:edit, :update, :destroy]

  inherit_resources
  respond_to :html, :json

  def new
    @activity = Activity.new( date: Date.today.strftime("%Y-%m-%d"))
  end

  def create
    descriptions = []

    if params[:activity][:descriptions].present? && params[:activity][:descriptions].any?
      descriptions = params[:activity][:descriptions].select{ |d| !d.blank? }
    end

    params[:activity].delete(:descriptions)

    if descriptions.any? && descriptions.size > 1
      @activities = []

      descriptions.each do |description|
        activity             = Activity.new(params[:activity])
        activity.user        = current_user
        activity.description = description

        if activity.save
          @activities << activity
        end
      end

      respond_to do |format|
        format.html { redirect_to collection_path }
        format.json { render json: @activities , status: :created }
      end
    else
      @activity = Activity.new params[:activity]
      @activity.description = descriptions.first
      @activity.user_id     = current_user.id

      if @activity.save
        respond_to do |format|
          format.html { redirect_to collection_path }
          format.json { render json: @activity , status: :created }
        end
      else
        headers["Access-Control-Allow-Origin"] = '*'
        respond_with @activity
        #respond_to do |format|
        #  format.html { render :edit }
        #  format.json { render json: { errors: @activity.errors, status: :unprocessable_entity}  }
        #end
      end
    end
  end

  def update
    @activity.update_attributes params[:activity]

    if @activity.save
      respond_to do |format|
        format.html { redirect_to collection_path }
        format.json { render json: @activity , status: :created }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: { errors: @activity.errors, status: :unprocessable_entity}  }
      end
    end
  end

protected

  def collection
    @collection = Activity.latest(current_user)
  end

  def load_resource
    @activity = current_user.activities.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!, except: [ :show ]
  before_filter :load_categories, only: [ :index, :show ]

  def index
    period_start, period_end = Report.date_range(params[:period])
    @activities = Activity.for_report(current_user, period_start, period_end)
  end

  def new
    period_start, period_end = Report.date_range(params[:period])
    @report = Report.new
    @report.period_start = period_start
    @report.period_end   = period_end
  end

  def show
    @report = Report.find_by_key(params[:id])
    @activities = Activity.for_report(@report.user, @report.period_start, @report.period_end)
    render :index
  end

  def create
    @report = Report.new(params[:report])
    @report.user = current_user

    if @report.save
      redirect_to root_path, notice: "Report was successfully sent to #{@report.email}"
    else
      render :new
    end
  end

protected

  def load_categories
    @categories = Category.all
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :json, :html
  skip_before_filter :verify_authenticity_token, :only => :create

  def create
    respond_to do |format|
      format.html {
        super
      }
      format.json {
        build_resource
        if resource.save
          render :status => 200, :json => resource
        else
          render :json => resource.errors, :status => :unprocessable_entity
        end
      }
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_create_report_form?
    action_name.eql?('index')
  end
end

app/views/activities/_form.html.haml
= simple_form_for @activity, html: { class: 'form-horizontal' } do |f|
  = f.association :category, label: "What", required: false, input_html: { class: 'form-control' }
  = f.input :date, required: false, as: :string, input_html: { class: 'form-control' }
  - if @activity.persisted?
    = f.input :description, as: :string, required: false, input_html: { class: 'form-control' }
  - else
    .descriptions
      = f.input :description, as: :string, required: false, input_html: { name: 'activity[descriptions][]', class: 'form-control' }
    %br
    .pull-right
      = link_to ' add description', 'javascript:', class: 'icon-plus controls'

  %hr
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = link_to t('.cancel', default: t('helpers.links.cancel')), activities_path, class: 'btn'
    - if @activity.persisted?
      = link_to 'Delete', activity_path(@activity), method: :delete, class: 'btn btn-danger', confirm: 'Are you sure you want to delete entry?'

.template.hidden
  .control-group.string.optional
    %label.string.optional.control-label{ for: 'activity_description' } Description
    .controls
      %input#activity_description.string.optional{ name: 'activity[descriptions][]', size: '50', type: 'text', value: '', class: 'form-control' }
      = link_to 'javascript:' do
        %span{ class: 'icon-trash' } &nbsp;

app/views/activities/edit.html.haml
.page-header
  %h1 Edit Item

.col-md-4
  = render "form"

app/views/activities/index.html.haml
.span6
  .page-header
    %h1
      Food tracker
      %small.pull-right= link_to 'ADD', new_activity_path, class: 'btn btn-large btn-primary'

  - if collection.any?
    .activities.well
      - collection.each do |date, categories|
        .activity
          %hr
          .row.show-grid
            .span3
              %h3= date.to_date.strftime('%A')
            .span3.date
              %span.label.label-info.pull-right= date.to_date.strftime('%e %b %Y')
          %hr
          .row
            - categories.each do |category_id, items|
              - category = Category.find(category_id)
              - if category.is_weight?
                %dl.dl-horizontal
                  %dt= category.name
                  %dd
                    = items.last[1]
                    = link_to 'edit', edit_activity_path(items.last[0]), class: 'edit btn btn-xs btn-primary pull-right'

              - else
                %dl
                  %dt= category.name
                  %dd
                    %ul.unstyled
                      - items.each do |id, description|
                        %li
                          = description
                          = link_to 'edit', edit_activity_path(id), class: 'edit  btn btn-xs btn-primary pull-right'

  - else
    No activities yet.
    = link_to 'Add activity', new_activity_path

app/views/activities/new.html.haml
.page-header
  %h1 Add Item

.col-md-4
  = render "form"

app/views/activities/show.html.haml
- model_class = @activity.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @activity.user_id
%p
  %strong= model_class.human_attribute_name(:category_id) + ':'
  %br
  = @activity.category_id
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @activity.description

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), activities_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_activity_path(@activity), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), activity_path(@activity), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : 'FoodTracker'
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag 'http://html5shim.googlecode.com/svn/trunk/html5.js'
    = stylesheet_link_tag 'application', media: 'all'
    = airbrake_javascript_notifier

    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      %nav.navbar.navbar-default
        .container
          .row
            .container-fluid
              .navbar-header
                %button.navbar-toggle.collapsed{ type: 'button', data: { target: '.nav-collapse', toggle: 'collapse' } }
                  %span.icon-bar
                  %span.icon-bar
                  %span.icon-bar
                %a.navbar-brand{ href: root_path } FoodTracker
              .collapse.navbar-collapse
                %ul.nav.navbar-nav.pull-right
                  - if user_signed_in?
                    %li= link_to 'Reports', reports_path
                    %li= link_to current_user.email, '#'
                    %li= link_to 'Sign out', destroy_user_session_path, method: :delete
                  - else
                    %li= link_to 'Sign in', new_user_session_path

    .container
      .content
        .row
          .col-md-9
            = yield
          .col-md-3
            -#.well.sidebar-nav
              / %h3 Sidebar
              / %ul.nav.nav-list
              /   %li.nav-header Sidebar
              /   %li= link_to 'Link 1', '/path1'
              /   %li= link_to 'Link 2', '/path2'
              /   %li= link_to 'Link 3', '/path3'

    %footer.footer
      .container
        %p.text-center &copy; Company 2012

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag 'application'
    = yield(:javascript)

app/views/reports/_form.html.haml
.col-md-5
  = simple_form_for @report, html: { class: 'form-horizontal' } do |f|
    = f.input :period_start, as: :hidden
    = f.input :period_end, as: :hidden
    = f.input :email, input_html: { class: 'form-control' }
    = f.input :subject, input_html: { class: 'form-control' }
    = f.input :comments, input_html: { class: 'form-control', rows: 5 }
    %br
    = f.submit 'Send Report', class: 'btn btn-success'

app/views/reports/index.html.haml
.report
  - if @activities.any?
    - if display_create_report_form?
      %p
        = form_tag new_report_path, method: :get do |f|
          .col-md-4
            = select_tag :period, options_for_select(Report::PERIODS, params[:period]), class: 'form-control'
          = submit_tag 'Send email', class: 'btn btn-success'

    %table.table.table-bordered
      %tr.well
        %th.day Day
        - @categories.each do |category|
          %th= category.name
      - @activities.each do |date, activities_by_category|
        %tr
          %td= date.to_date.strftime("%A %e %b %Y")
          - @categories.each do |category|
            %td
              - if activities_by_category[category.id].present?
                %ul.unstyled
                  - activities_by_category[category.id].each do |item|
                    %li= item
  - else
    %h2.text-center No activities

app/views/reports/new.html.haml
.page-header
  %h1 Create report

= render 'form'